from .baden_baden import ParkingBadenBaden
from .bielefeld import ParkingBielefeld
from .bonn import ParkingBonn
from .braunschweig import ParkingBraunschweig
from .bremen import ParkingBremen
from .dortmund import ParkingDortmund
from .dresden import ParkingDresden
from .ffh import ParkingFFH
from .hanau import ParkingHanau
from .ingolstadt import ParkingIngolstadt
from .karlsruhe import ParkingKarlsruhe
from .koeln import ParkingKoeln
from .konstanz import ParkingKonstanz
from .luebeck import ParkingLuebeck
from .mannheim import ParkingMannheim
from .muenster import ParkingMuenster
from .nuernberg import ParkingNuernberg
from .oldenburg import ParkingOldenburg
from .osnabrueck import ParkingOsnabrueck
from .paderborn import ParkingPaderborn
from .regensburg import ParkingRegensburg
from .reutlingen import ParkingReutlingen
from .potsdam import ParkingPotsdam
from .trier import ParkingTrier
from .ulm import ParkingUlm
from .ulm_uni import ParkingUlmUni
from .wiesbaden import ParkingWiesbaden
