from .bonn import ParkingBonn
from .dortmund import ParkingDortmund
from .dresden import ParkingDresden
from .ffh import ParkingFFH
from .koeln import ParkingKoeln
from .luebeck import ParkingLuebeck
from .muenster import ParkingMuenster
from .oldenburg import ParkingOldenburg
from .paderborn import ParkingPaderborn
from .ulm import ParkingUlm
from .ulm_uni import ParkingUlmUni
from .wiesbaden import ParkingWiesbaden
